import type { Metadata } from "next";

// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dropzone/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Inter } from "next/font/google";

//Import global styles at last to override all mantine styles
import "./globals.css";
import Header from "@/components/Header";
import TrpcProvider from "@/trpc/Provider";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin-ext"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};
export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<head>
				<ColorSchemeScript defaultColorScheme="dark" />
			</head>
			<body className={`${inter.variable}`}>
				<MantineProvider>
					<TrpcProvider>
						<Header />
						{children}
					</TrpcProvider>
				</MantineProvider>
			</body>
		</html>
	);
}
